routes/web.php
<?php

    /*
    |--------------------------------------------------------------------------
    | Web Routes
    |--------------------------------------------------------------------------
    |
    | Here is where you can register web routes for your application. These
    | routes are loaded by the RouteServiceProvider within a group which
    | contains the "web" middleware group. Now create something great!
    |
    */
    //
    // Route::get('/', function () {
    //    return view('welcome');
    // });

    Auth::routes();

    //Route::get('/home', 'HomeController@index')->name('home');

    //Check button , jquery.uniform.js->654 line,diseble

    /*
    |--------------------------------------------------------------------------
    | Admin Register,Login,Admin Dashboard part
    |--------------------------------------------------------------------------
    */
    //Admin Register
//    Route::view('admin/register','auth.admin-register');
//    Route::post('admin/registration','AdminController@adminregistration')->name('admin.registration');

    //admin Login
    Route::get('admin/login','AdminController@loginform');
    Route::post('admin/dashboard','AdminController@adminLogin')->name('admin.login');

    //Admin Dashboard after login
    Route::group(['middleware'=>['CheckRole']], function (){
    Route::get('admin/dashboard','AdminController@dashboard')->name('admin.dashboard');
    Route::get('admin/settings','AdminController@settings')->name('admin.settings');
    Route::get('/admin/check-pwd','AdminController@chkPassword');
    Route::post('/admin/update-pwd','AdminController@updatePassword');
    // Admin Category
    Route::get('admin/add-category','CategoryController@category')->name('category');
    Route::post('admin/add-category','CategoryController@addcategory')->name('add.category');
    Route::get('admin/view-category','CategoryController@viewcategory')->name('view.category');
    Route::get('admin/{id}/edit-category','CategoryController@editcategory')->name('edit.category');
    Route::post('admin/{id}/update-category','CategoryController@updatecategory')->name('update.category');
    Route::get('admin/{id}/delete-category','CategoryController@deletecategory')->name('delete.category');

    //Products
    Route::get('admin/add-product','ProductsController@product')->name('product');
    Route::post('admin/add-product','ProductsController@addproduct')->name('add.product');
    Route::get('admin/view-product','ProductsController@viewproduct')->name('view.product');
    Route::get('admin/{id}/edit-product','ProductsController@editproduct')->name('edit.product');
    Route::post('admin/{id}/update-product','ProductsController@updateproduct')->name('update.product');
    Route::get('admin/{id}/delete-product','ProductsController@deleteproduct')->name('delete.product');
    Route::get('/admin/delete-product-image/{id}','ProductsController@deleteProductImage')->name('deleteimage');
    Route::get('/admin/delete-product-video/{id}','ProductsController@deleteProductVideo')->name('delete_video');


    //Products Attribute
    Route::get('admin/{id}/attribute','ProductsController@product_attribute')->name('product_attribute');
    Route::post('admin/{id}/{product_code}/add_attribute','ProductsAttributeController@product_store_attribute')->name('product_store_attribute');
    Route::get('admin/view/attribute','ProductsAttributeController@product_view_attribute')->name('product_view_attribute');
    Route::get('/admin/{id}/delete-attribute','ProductsAttributeController@deleteattribute')->name('deleteattribute');
    Route::post('/admin/{id}/update-attribute','ProductsAttributeController@updateattribute')->name('updateattribute');

    //Products Multiple Image Add
    Route::get('admin/{id}/multiple-images','ProductsController@add_multiple_images')->name('add_multiple_images');
    Route::post('admin/{id}/multiple-images','Product_image_Controller@image_store')->name('image_store');
    Route::get('admin/view/images','Product_image_Controller@Product_view_images')->name('product_view_images');
    Route::get('admin/{id}/delete-image','Product_image_Controller@delete_image')->name('delete_image');


     //Coupon
    Route::get('coupon/cart/coupon','CouponController@coupon')->name('coupon');
    Route::post('coupon/cart/coupon','CouponController@add_coupon')->name('add_coupon');
    Route::get('coupon/cart/view-coupon','CouponController@view_coupon')->name('view_coupon');
    Route::get('coupon/cart/{id}/edit-coupon','CouponController@edit_coupon')->name('edit_coupon');
    Route::post('coupon/cart/{id}/update-coupon','CouponController@update_coupon')->name('update_coupon');
    Route::get('coupon/cart/{id}/delete-coupon','CouponController@delete_coupon')->name('delete_coupon');


    // View User Order Product

    Route::get('/admin/user/view-orders','UserOrderProductController@viewOrders')->name('viewOrders');
    Route::get('/admin/user/view-order/{order_id}','UserOrderProductController@viewOrderDetails')->name('viewOrderDetails');
    Route::post('/admin/user/update-order-status','UserOrderProductController@updateOrderStatus')->name('updateOrderStatus');
    Route::get('/admin/user/view-order-invoice/{order_id}','UserOrderProductController@viewOrderinvoice')->name('viewOrderinvoice');

    // View All User
    Route::get('/admin/user/all-user','registeredUser@all_user')->name('all_user');


    //cms page
    Route::get('admin/add/cms','CmspageController@cms')->name('cms');
    Route::post('admin/add/cms','CmspageController@add_cms')->name('add_cms');
    Route::get('admin/view/cms','CmspageController@view_cms')->name('view_cms');
    Route::get('admin/{id}/cms','CmspageController@edit_cms')->name('edit_cms');
    Route::post('admin/{id}/update-cms','CmspageController@update_cms')->name('update_cms');
    Route::get('admin/{id}/delete-cms','CmspageController@delete_cms')->name('delete_cms');

    //shipping page
    Route::get('admin/view-shipping','ShippingController@shipping')->name('shipping');
    Route::get('admin/{id}/view-shipping','ShippingController@edit_shipping')->name('edit_shipping');
    Route::post('admin/{id}/update-shipping','ShippingController@update_shipping')->name('update_shipping');


    // Admin -> sub Admin
    Route::get('admin/add-admin','AdminController@addAdmin')->name('addAdmin')  ;
    Route::post('admin/add-admin','AdminController@add_Admin_subadmin')->name('add_Admin_subadmin');
    Route::get('admin/view-admin-subadmin','AdminController@viewAdmin')->name('viewAdmin');
    Route::get('admin/edit/{id}/admin-sub-admin','AdminController@editAdmin_sub')->name('editAdmin_sub');
    Route::post('admin/update/{id}/admin-sub-admin','AdminController@updateAdmin_sub')->name('updateAdmin_sub');




    //Admin Logout
    Route::get('/admin-logout', 'AdminController@logout')->name('admin.logout');
    });







    /*
     |--------------------------------------------------------------------------
     | frontend  part
     |--------------------------------------------------------------------------
     */

    Route::get('/','IndexController@index')->name('home');

    //search product
    Route::get('/search/product','IndexController@search')->name('search');

    //Listing Page
    Route::get('/{url}','IndexController@listing')->name('listing');

    //products Details
    Route::get('product/{slug}','IndexController@productsdetails')->name('productsdetails');

    //Display cms page on Frontend
    //apply on front_footer.blade.php
    Route::match(['get','post'],'cms/page/{url}','IndexController@cmsPage');

    //Contact Us Page
    Route::get('page/contact-us','IndexController@contact_us')->name('contact_us');
    Route::post('page/contact-us','IndexController@send_contact_info')->name('send_contact_info');

    //filter












    /*
     |--------------------------------------------------------------------------
     | Cart
     |--------------------------------------------------------------------------
     */

    Route::post('product/add-cart','IndexController@addtocart')->name('addtocart'); //form
    Route::get('product/cart/view-cart','IndexController@cart')->name('cart'); //view
    //Update Quantity in cart
    Route::get('/cart/update-quantity/{product_id}/{quantity}','IndexController@updateCartQuantity');
    //Delete cart
    Route::get('product/cart/view-cart/{id}','IndexController@deletecart')->name('deletecart');
    //coupon code apply on add-cart  page
    Route::post('product/cart/apply-coupon','IndexController@apply_coupon')->name('apply_coupon');

    // Check Pincode
    Route::post('/check-pincode','IndexController@checkPincode');
    //Product Price
    Route::post('product/price/display_on_size','IndexController@price_display_on_size')->name('price_display_on_size');


    /*
    |--------------------------------------------------------------------------
    | User Registration,Login,Update-password,User Account
    |--------------------------------------------------------------------------
    */
   Route::get('login','UserController@login')->name('login');
   Route::get('register','UserController@register')->name('register');
   Route::post('user/registration','UserController@userregistration')->name('registration');
   Route::post('/','UserController@userLogin');

   //Email
    Route::get('confirm/{code}','UserController@confirmAccount');
   //Forgot Password
    Route::match(['get','post'],'user/password/forgot-password','UserController@forgotPassword');

    //coupon code apply on add-cart  page
    Route::post('product/cart/apply-coupon','IndexController@apply_coupon')->name('apply_coupon');

    //Display cms page on Frontend
    //apply on front_footer.blade.php
    Route::match(['get','post'],'cms/page/{url}','IndexController@cmsPage');
    //Contact Us Page
    Route::get('page/contact-us','IndexController@contact_us')->name('contact_us');

app/Cms.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cms extends Model
{
    protected $guarded=[];

}

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $guarded=[];

    public function category(){
        return $this->belongsTo('App\Category');
    }

    public function getBodyHtmlAttribute(){
        return \Parsedown::instance()->text($this->description);
    }

    public function product_attribute()
    {
        return $this->hasMany('App\Product_attribute');
    }



    //One To Many

    public function images(){
        return $this->hasMany('App\Product_image');

    }


    // slug
    public function setProductNameAttribute($value)
    {
        $this->attributes['product_name'] = $value;
        $this->attributes['slug'] = str_slug($value);
    }


    public function getUrlAttribute($value)
    {
        return route('productsdetails',$this->slug);
    }



    public static function getShippingCharges($total_weight,$country){
        $shippingDetails = ShippingCharge::where('country',$country)->first();
        if($total_weight>0){
            if($total_weight > 0 && $total_weight<=500){
                $shipping_charges = $shippingDetails->shipping_charges0_500g;
            }else if($total_weight>=501 && $total_weight<=1000){
                $shipping_charges = $shippingDetails->shipping_charges501_1000g;
            }else if($total_weight>=1001 && $total_weight<=2000){
                $shipping_charges = $shippingDetails->shipping_charges1001_2000g;
            }else if($total_weight>=2001 && $total_weight<=5000){
                $shipping_charges = $shippingDetails->shipping_charges2001_5000g;
            }else{
                $shipping_charges = 0;
            }
        }else{
            $shipping_charges = 0;
        }
        return $shipping_charges;
    }






}

resources/views/cms/cms_page.blade.php
@extends('layouts.adminLayout.admin_design')
@section('content')


<div id="content">
<div id="content-header">
<div id="breadcrumb"><a href="index.html" title="Go to Home" class="tip-bottom"><i class="icon-home"></i>
Home</a> <a href="#">CMS</a> <a href="#" class="current">Add CMS</a></div>
<h1>Add-CMS</h1>
</div>

@if(Session::has('error'))
<div class="alert alert-error alert-block">
<button type="button" class="close" data-dismiss="alert">×</button>
<strong>{!! session('error') !!}</strong>
</div>
@endif
@if(Session::has('success'))
<div class="alert alert-success alert-block">
<button type="button" class="close" data-dismiss="alert">×</button>
<strong>{!! session('success') !!}</strong>
</div>
@endif

<div class="container-fluid">
<hr>
<div class="row-fluid">
<div class="span12">
<div class="widget-box">
    <div class="widget-title"><span class="icon"> <i class="icon-info-sign"></i> </span>
        <h5>Add-CMS</h5>

    </div>
    <div class="widget-content nopadding">

        <form class="form-horizontal" method="post" action="{{route('add_cms')}}" name="add_cms"
              id="add_cms" novalidate="novalidate">
            @csrf


            <div class="control-group">
                <label class="control-label">Title</label>
                <div class="controls">
                    <input type="text" id="title"
                           class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}"
                           name="title" value="{{ old('title') }}" required>
                    @if ($errors->has('title'))
                        <span class="invalid-feedback" role="alert">
                         <strong>{{ $errors->first('title') }}</strong>
                          </span>
                    @endif
                </div>
            </div>


            <div class="control-group">
                <label class="control-label">URL</label>
                <div class="controls">
                    <input type="text" id="url"
                           class="form-control{{ $errors->has('url') ? ' is-invalid' : '' }}"
                           name="url" value="{{ old('url') }}" required>

                    @if ($errors->has('url'))
                        <span class="invalid-feedback" role="alert">
                         <strong>{{ $errors->first('url') }}</strong>
                          </span>
                    @endif

                </div>
            </div>


            <div class="control-group">
                <label class="control-label">CMS Description</label>
                <div class="controls">
                    <textarea
                        class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}"
                        name="description" value="{{ old('description') }}" required></textarea>
                    @if ($errors->has('description'))
                        <span class="invalid-feedback" role="alert">
                         <strong>{{ $errors->first('description') }}</strong>
                          </span>
                    @endif
                </div>
            </div>

            <div class="control-group">
                <label class="control-label">Meta Title</label>
                <div class="controls">
                    <input type="text" id="meta_title" class="form-control" name="meta_title"  >

                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Meta Description</label>
                <div class="controls">
                    <input type="text" id="meta_description" class="form-control" name="meta_description"  >
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Meta Keywords</label>
                <div class="controls">
                    <input type="text" id="meta_keywords" class="form-control" name="meta_keywords"  >

                </div>
            </div>


            <div class="control-group">
                <label class="control-label">Enable</label>
                <div class="controls">
                    <input type="checkbox" name="status" id="status" value="1">
                </div>
            </div>

            <div class="form-actions">
                <input type="submit" value="submit" class="btn btn-success">
            </div>
        </form>


    </div>
</div>
</div>
</div>

</div>
</div>


@endsection

resources/views/cms/edit_cms.blade.php
@extends('layouts.adminLayout.admin_design')
@section('content')


    <div id="content">
        <div id="content-header">
            <div id="breadcrumb"><a href="index.html" title="Go to Home" class="tip-bottom"><i class="icon-home"></i>
                    Home</a> <a href="#">CMS</a> <a href="#" class="current">Update CMS</a></div>
            <h1>Update-CMS</h1>
        </div>

        @if(Session::has('error'))
            <div class="alert alert-error alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <strong>{!! session('error') !!}</strong>
            </div>
        @endif
        @if(Session::has('success'))
            <div class="alert alert-success alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <strong>{!! session('success') !!}</strong>
            </div>
        @endif

        <div class="container-fluid">
            <hr>
            <div class="row-fluid">
                <div class="span12">
                    <div class="widget-box">
                        <div class="widget-title"><span class="icon"> <i class="icon-info-sign"></i> </span>
                            <h5>Update-CMS</h5>

                        </div>
                        <div class="widget-content nopadding">


                            <form class="form-horizontal" method="post"  name="add_cms"
                                  id="add_cms"  action="{{route('update_cms',$cms->id)}}" novalidate="novalidate">
                                @csrf


                                <div class="control-group">
                                    <label class="control-label">Title</label>
                                    <div class="controls">
                                        <input type="text" id="title"
                                               class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}"
                                               name="title" value="{{$cms->title}}"  required>
                                        @if ($errors->has('title'))
                                            <span class="invalid-feedback" role="alert">
                         <strong>{{ $errors->first('title') }}</strong>
                          </span>
                                        @endif
                                    </div>
                                </div>


                                <div class="control-group">
                                    <label class="control-label">URL</label>
                                    <div class="controls">
                                        <input type="text" id="url"
                                               class="form-control{{ $errors->has('url') ? ' is-invalid' : '' }}"
                                               name="url" value="{{$cms->url}}" required>

                                        @if ($errors->has('url'))
                                            <span class="invalid-feedback" role="alert">
                         <strong>{{ $errors->first('url') }}</strong>
                          </span>
                                        @endif

                                    </div>
                                </div>


                                <div class="control-group">
                                    <label class="control-label">CMS Description</label>
                                    <div class="controls">
                    <textarea
                        class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}"
                        name="description" value="{{ old('description') }}" required>{{$cms->description}}</textarea>
                                        @if ($errors->has('description'))
                                            <span class="invalid-feedback" role="alert">
                         <strong>{{ $errors->first('description') }}</strong>
                          </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label">Meta Title</label>
                                    <div class="controls">
                                        <input type="text" id="meta_title" class="form-control" name="meta_title" value="{{$cms->meta_title}}" >

                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label">Meta Description</label>
                                    <div class="controls">
                                        <input type="text" id="meta_description" class="form-control" name="meta_description" value="{{$cms->meta_description}}" >

                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label">Meta Keywords</label>
                                    <div class="controls">
                                        <input type="text" id="meta_keywords" class="form-control" name="meta_keywords" value="{{$cms->meta_keywords}}" >

                                    </div>
                                </div>


                                <div class="control-group">
                                    <label class="control-label">Enable</label>
                                    <div class="controls">
                                        <input type="checkbox" name="status" id="status" @if($cms_status->status == "1") checked @endif value="1">
                                    </div>
                                </div>

                                <div class="form-actions">
                                    <input type="submit" value="Update" class="btn btn-success">
                                </div>
                            </form>


                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>


@endsection

resources/views/cms/view_cms_page.blade.php
@extends('layouts.adminLayout.admin_design')
@section('content')


<div id="content">
<div id="content-header">
<div id="breadcrumb"><a href="index.html" title="Go to Home" class="tip-bottom"><i class="icon-home"></i>
    Home</a> <a href="#">CMS</a> <a href="#" class="current">View CMS</a></div>
<h1>View CMS</h1>
</div>


@if(Session::has('error'))
<div class="alert alert-error alert-block">
<button type="button" class="close" data-dismiss="alert">×</button>
<strong>{!! session('error') !!}</strong>
</div>
@endif
@if(Session::has('success'))
<div class="alert alert-success alert-block">
<button type="button" class="close" data-dismiss="alert">×</button>
<strong>{!! session('success') !!}</strong>
</div>
@endif


<div class="container-fluid">
<hr>
<div class="row-fluid">
<div class="span12">

    <div class="widget-box">
        <div class="widget-title"><span class="icon"><i class="icon-th"></i></span>
            <h5>View CMS</h5>
        </div>
        <div class="widget-content nopadding">
            <table class="table table-bordered data-table">
                <thead>
                <tr>
                    <th>CMS ID</th>
                    <th>Title</th>
                    <th>Url</th>
                    <th>Description</th>
                    <th>Status</th>
                    <th>Created At</th>
                    <th>Action</th>
                </tr>
                </thead>

                <tbody>
                @foreach($cms_pages as $cms)

                    <tr class="gradeX">
                        <td>{{$cms->id}}</td>
                        <td>{{str_limit($cms->title,15)}}</td>
                        <td>{{str_limit($cms->url,10)}}</td>
                        <td>{{ str_limit($cms->description,25)}}</td>
                        <td>
                            @if($cms->status===1)
                                <h6 class="text-success font-weight-bold">1</h6>

                            @else
                                <h6 class="text-warning font-weight-bold">0</h6>
                            @endif

                        </td>
                        <td>{{$cms->created_at}}</td>


                        <td class="center">
                            <a href="#exampleModal{{$cms->id}}" data-toggle="modal"
                               data-target="#exampleModal{{$cms->id}}" class="btn btn-success btn-mini"
                               title="View cms">View</a>
                            <a href="{{route('edit_cms',$cms->id)}}" class="btn btn-primary btn-mini ">Edit</a>
                            &nbsp;
                            <a href="{{route('delete_cms',$cms->id)}}"
                               onclick="return confirm('Are you sure you want to delete this item?');"
                               class="btn btn-danger btn-mini ">Delete</a> &nbsp;

                        </td>

                    </tr>


                    <div class="modal fade" id="exampleModal{{$cms->id}}" tabindex="-1" role="dialog"
                         aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">{{$cms->title}}</h5>
                                    {{--                                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">--}}
                                    {{--                                                                            <span aria-hidden="true">&times;</span>--}}
                                    {{--                                                                        </button>--}}
                                </div>
                                <div class="modal-body">

                                    <p>cms ID : <b>{{$cms->id}} </b></p>
                                    <p>Meta Title : <b>{{ str_limit($cms->meta_title, 40)}}</b></p>
                                    <p>Meta Description :
                                        <b>{{ str_limit($cms->meta_description, 40)}} </b></p>
                                    <p>Meta Keywords :<b>$ {{$cms->meta_keywords}}</b></p>

                                    Description : {!! $cms->body_html !!}

                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-danger btn-mini"
                                            data-dismiss="modal">Close
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>

                @endforeach
                </tbody>

            </table>
        </div>
    </div>
</div>
</div>
</div>
</div>


@endsection